# Startup and workspace change commands
# Run Sketchybar together with AeroSpace
# sketchbar has a built-in detection of already running process,
# so it won't be run twice on AeroSpace restart
after-startup-command = ['exec-and-forget sketchybar']

start-at-login = true

# Notify Sketchybar about workspace change
exec-on-workspace-change = [
    '/bin/bash',
    '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED=$AEROSPACE_FOCUSED_WORKSPACE',
]

# Gaps between windows
[gaps]
inner.horizontal = 8
inner.vertical = 8

# Gaps between windows and monitor edges
outer.left = 8
outer.right = 8
outer.top = 8
outer.bottom = 8

# Key mapping preset (required)
[key-mapping]
preset = 'qwerty'

# Key bindings section
[mode.main.binding]
# Focus windows using vim keys
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Move windows using vim keys
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Assign specific applications to workspaces on launch
[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = 'move-node-to-workspace T'

[[on-window-detected]]
if.app-id = 'com.mit.Chrome'
run = 'move-node-to-workspace W'

# Make certain windows float by default
[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = 'layout floating'
